# Generated by Django 5.1.7 on 2025-03-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtomodel",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="image/product/%y/%m/%d",
                verbose_name="Imagem",
            ),
        ),
    ]
